# Generated by Django 3.2.17 on 2023-10-18 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalwork',
            name='area_user',
        ),
        migrations.RemoveField(
            model_name='historicalwork',
            name='assigned_user',
        ),
        migrations.RemoveField(
            model_name='work',
            name='area_user',
        ),
        migrations.RemoveField(
            model_name='work',
            name='assigned_user',
        ),
    ]
