# Generated by Django 3.2.17 on 2023-02-07 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('territories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('property_key', models.CharField(max_length=10, unique=True, verbose_name='Clave')),
                ('sirh', models.CharField(blank=True, max_length=10, null=True, verbose_name='Convenio o SIRH')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inmubles', to='clients.client', verbose_name='Cliente')),
                ('locality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='territories.locality', verbose_name='Localidad')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territories.municipality', verbose_name='Municipio')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='territories.province', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Inmueble',
                'verbose_name_plural': 'Inmuebles',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProperty',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(blank=True, editable=False, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('property_key', models.CharField(db_index=True, max_length=10, verbose_name='Clave')),
                ('sirh', models.CharField(blank=True, max_length=10, null=True, verbose_name='Convenio o SIRH')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Dirección')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('client', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clients.client', verbose_name='Cliente')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locality', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='territories.locality', verbose_name='Localidad')),
                ('municipality', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='territories.municipality', verbose_name='Municipio')),
                ('province', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='territories.province', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'historical Inmueble',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
