# Generated by Django 3.2.17 on 2023-04-07 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluploadfileform',
            name='name',
        ),
        migrations.RemoveField(
            model_name='uploadfileform',
            name='name',
        ),
    ]
