# Generated by Django 3.2.17 on 2023-04-10 02:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0003_auto_20230409_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaluploadfileform',
            name='changed_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='uploadfileform',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_by', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
