# Generated by Django 3.2.17 on 2023-10-05 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beneficiary', '0001_initial'),
        ('resources', '0005_auto_20230920_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalresource',
            name='beneficiary',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='beneficiary.beneficiary', verbose_name='Beneficiario'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='beneficiary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='beneficiary.beneficiary', verbose_name='Beneficiario'),
        ),
    ]
