# Generated by Django 3.2.17 on 2023-10-11 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_auto_20231004_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalresource',
            name='request',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='request',
        ),
    ]
