# Generated by Django 3.2.17 on 2023-11-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_auto_20231010_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalresource',
            name='detail_state',
            field=models.CharField(blank=True, choices=[('expectantes', 'En espera del coordinador para indicar la forma de pago.'), ('expectante', 'En espera de recursos por parte del cliente.'), ('aguardando', 'En espera de movimiento por parte del área de cuentas.')], max_length=244, verbose_name='Detalle del estado'),
        ),
        migrations.AddField(
            model_name='historicalresource',
            name='invoiced',
            field=models.BooleanField(default=False, verbose_name='Facturado'),
        ),
        migrations.AddField(
            model_name='resource',
            name='detail_state',
            field=models.CharField(blank=True, choices=[('expectantes', 'En espera del coordinador para indicar la forma de pago.'), ('expectante', 'En espera de recursos por parte del cliente.'), ('aguardando', 'En espera de movimiento por parte del área de cuentas.')], max_length=244, verbose_name='Detalle del estado'),
        ),
        migrations.AddField(
            model_name='resource',
            name='invoiced',
            field=models.BooleanField(default=False, verbose_name='Facturado'),
        ),
        migrations.AlterField(
            model_name='historicalresource',
            name='bank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='historicalresource',
            name='concept',
            field=models.TextField(blank=True, verbose_name='Concepto de pago'),
        ),
        migrations.AlterField(
            model_name='historicalresource',
            name='transfer_data',
            field=models.TextField(default='{}', verbose_name='Datos transferencia'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='bank',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Banco'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='concept',
            field=models.TextField(blank=True, verbose_name='Concepto de pago'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='transfer_data',
            field=models.TextField(default='{}', verbose_name='Datos transferencia'),
        ),
    ]
