# Generated by Django 3.2.17 on 2023-11-23 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0010_auto_20231122_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluploadfileform',
            name='type_file',
            field=models.CharField(choices=[('comprobante', 'Comprobante'), ('factura', 'Factura')], default='comprobante', max_length=30, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='uploadfileform',
            name='type_file',
            field=models.CharField(choices=[('comprobante', 'Comprobante'), ('factura', 'Factura')], default='comprobante', max_length=30, verbose_name='Tipo de documento'),
        ),
    ]
