# Generated by Django 3.2.17 on 2023-10-18 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('territories', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='Apellidos')),
                ('phone_one', models.CharField(max_length=15, unique=True, verbose_name='Número telefónico 1')),
                ('phone_two', models.CharField(default='', max_length=15, verbose_name='Número telefónico 2')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Correo electrónico')),
                ('municipality', models.ManyToManyField(related_name='users_field', to='territories.Municipality', verbose_name='Municipio')),
            ],
            options={
                'verbose_name': 'Usuario en campo',
                'verbose_name_plural': 'Usuarios en campo',
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateField(auto_now=True, verbose_name='Fecha de eliminación')),
                ('charge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='provinces_charge', to=settings.AUTH_USER_MODEL, verbose_name='Usuario a cargo')),
                ('province', models.ManyToManyField(related_name='users_charge', to='territories.Province', verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Usuario a cargo',
                'verbose_name_plural': 'Usuarios a cargo',
            },
        ),
    ]
