# Generated by Django 3.2.17 on 2023-11-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territories', '0001_initial'),
        ('users', '0002_charge_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charge',
            name='province',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='municipality',
        ),
        migrations.AddField(
            model_name='charge',
            name='provinces',
            field=models.ManyToManyField(related_name='users_charge', to='territories.Province', verbose_name='Estados'),
        ),
        migrations.AddField(
            model_name='contact',
            name='municipalities',
            field=models.ManyToManyField(related_name='users_field', to='territories.Municipality', verbose_name='Municipios'),
        ),
    ]
