# Generated by Django 3.2.17 on 2023-02-07 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40, unique=True, verbose_name='Estado')),
                ('key', models.CharField(max_length=2, null=True)),
                ('abbreviation', models.CharField(max_length=10, null=True, unique=True, verbose_name='Abreviatura')),
                ('active', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Estado',
                'verbose_name_plural': 'Estados',
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=3, null=True)),
                ('name', models.CharField(max_length=100, verbose_name='Municipio')),
                ('active', models.IntegerField(default=1)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='municipalities', to='territories.province')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
            },
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=4)),
                ('name', models.CharField(max_length=100, verbose_name='Localidad')),
                ('carta', models.CharField(blank=True, max_length=10)),
                ('active', models.IntegerField(default=1)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locality', to='territories.municipality')),
            ],
            options={
                'verbose_name': 'Localidad',
                'verbose_name_plural': 'Localidades',
            },
        ),
    ]
